### ISSUE TITLE
Does this duplicate the work in nodesource/ansible-nodejs-role?

### ISSUE THREAD

**Issue by conorgil** [haikulab/ansible-nodejs#1]
Not sure if you are aware, but it looks like NodeSource is maintaining an ansible role to install NodeJS here: https://github.com/nodesource/ansible-nodejs-role.

Is this role a duplicate of that effort?

**Comment by sergeifilippov** [comment]
Thanks @conorgil 

Looks like their version is more fully featured.

Closing.

**Comment by conorgil** [comment]
No worries. I just came across both and figured I would let you know.

Thanks for contributing back to the community!
